TestForOski/Controllers/QestAuthorizedUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestForOski.Models;
using TestForOski.MyHelper;

namespace TestForOski.Controllers
{
    public class QestAuthorizedUserController : Controller
    {
        TestContext db = new TestContext();

        public RedirectToRouteResult PageQuest()
        {
            return RedirectToRoute(new { controller = "Question", action = "PageQuest1" });
        }
   
        // GET: Question

        public ActionResult PageQuest1()
        {
            IEnumerable<Question> questions = db.Questions;
            ViewBag.Questions = questions;
            return View();

        }
        [HttpPost]
        public ActionResult PageQuest1(CheckBoxModel boxModel)
        {
            bool value = boxModel.Status;
            ViewBag.Status = value;

            if (value == true)
            {
              
            }
            IEnumerable<Question> questions = db.Questions;
            ViewBag.Questions = questions;
            return View();

        }

        public ActionResult PageQuest2()
        {
            IEnumerable<Question> questions = db.Questions;
            ViewBag.Questions = questions;
            return View();
        }
        [HttpPost]
        public ActionResult PageQuest2(CheckBoxModel boxModel)
        {
            bool value = boxModel.Status;
            ViewBag.Status = value;

            if (value == true)
            {

            }
            IEnumerable<Question> questions = db.Questions;
            ViewBag.Questions = questions;
            return View();

        }
        public ActionResult PageQuest3()
        {
            IEnumerable<Question> questions = db.Questions;
            ViewBag.Questions = questions;
            return View();
        }
        [HttpPost]
        public ActionResult PageQuest3(CheckBoxModel boxModel)
        {
            bool value = boxModel.Status;
            ViewBag.Status = value;

            if (value == true)
            {

            }
            IEnumerable<Question> questions = db.Questions;
            ViewBag.Questions = questions;
            return View();

        }
        public ActionResult PageQuest4()
        {
            IEnumerable<Question> questions = db.Questions;
            ViewBag.Questions = questions;
            return View();

        }
        [HttpPost]
        public ActionResult PageQuest4(CheckBoxModel boxModel)
        {
            bool value = boxModel.Status;
            ViewBag.Status = value;

            if (value == true)
            {

            }
            IEnumerable<Question> questions = db.Questions;
            ViewBag.Questions = questions;
            return View();

        }
        public ActionResult PageQuest5()
        {
            IEnumerable<Question> questions = db.Questions;
            ViewBag.Questions = questions;
            return View();
        }
        [HttpPost]
        public ActionResult PageQuest5(CheckBoxModel boxModel)
        {
            bool value = boxModel.Status;
            ViewBag.Status = value;

            if (value == true)
            {

            }
            IEnumerable<Question> questions = db.Questions;
            ViewBag.Questions = questions;
            return View();

        }
        public ActionResult PageQuest6()
        {
            IEnumerable<Question> questions = db.Questions;
            ViewBag.Questions = questions;
            return View();
        }
        [HttpPost]
        public ActionResult PageQuest6(CheckBoxModel boxModel)
        {
            bool value = boxModel.Status;
            ViewBag.Status = value;

            if (value == true)
            {

            }
            IEnumerable<Question> questions = db.Questions;
            ViewBag.Questions = questions;
            return View();

        }
        [HttpPost]
        public ActionResult PageQuest(CheckBoxModel boxModel)
        {
            bool value = boxModel.Status;
            ViewBag.Status = value;

            if (value == true)
            {

            }
     
            return View();

        }
        
    }
}

TestForOski/Views/QestAuthorizedUser/PageQuest1.cshtml
@model TestForOski.Models.CheckBoxModel
<h2>Тест по математике </h2>

@{
    List<string> quest = new List<string>();
    foreach (var q in ViewBag.Questions)
    {
        if (q.IdCategory == 1)
        {
            // Собрали вопросы из конкретной категории
            quest.Add(q.Text);

        }
    }
}
<h2 style="color:maroon">Первый вопрос :</h2>

@for (int i = 0; i < quest.Count; i++)
{
    if (i == 0)
    {
        <h3>@quest[0]</h3>
    }

}
@using (Html.BeginForm("PageQuest1", "QestAuthorizedUser"))
{
    @Html.CheckBox("answer1", false) @Html.Label(" 8 ")
    <br />
    @Html.CheckBoxFor(m => m.Status, false) @Html.Label(" 4 ")
    <br />
    @Html.CheckBox("answer3", false) @Html.Label(" 9 ")
    <br />
    <input type="submit" value="Сохранить" />

}
<br />
<br />
<a class=" btn btn-default" href="~/QestAuthorizedUser/PageQuest2">Продолжить</a>
<h3>@ViewBag.Status</h3>

TestForOski/Views/QestAuthorizedUser/PageQuest2.cshtml
@model TestForOski.Models.CheckBoxModel
<h2>Тест по математике </h2>

@{
    List<string> quest = new List<string>();
    foreach (var q in ViewBag.Questions)
    {
        if (q.IdCategory == 1)
        {
            // Собрали вопросы из конкретной категории
            quest.Add(q.Text);

        }
    }
}
<h2 style="color:maroon">Второй вопрос :</h2>

@for (int i = 0; i < quest.Count; i++)
{
    if (i == 1)
    {
        <h3>@quest[1]</h3>
    }

}
@using (Html.BeginForm("PageQuest2", "QestAuthorizedUser"))
{
    @Html.CheckBox("answer1", false) @Html.Label(" 10 ")
    <br />
    @Html.CheckBox("answer2", false) @Html.Label(" 8 ")
    <br />
    @Html.CheckBoxFor(m => m.Status, false) @Html.Label(" 15 ")
    <br />
    <input type="submit" value="Сохранить" />

}
<br />
<br />
<a class=" btn btn-default" href="~/QestAuthorizedUser/PageQuest3">Продолжить</a>
<h3>@ViewBag.Status</h3>

TestForOski/Views/QestAuthorizedUser/PageQuest3.cshtml
@model TestForOski.Models.CheckBoxModel
<h2>Тест по математике </h2>

@{
    List<string> quest = new List<string>();
    foreach (var q in ViewBag.Questions)
    {
        if (q.IdCategory == 1)
        {
            // Собрали вопросы из конкретной категории
            quest.Add(q.Text);

        }
    }
}
<h2 style="color:maroon">Последний вопрос :</h2>

@for (int i = 0; i < quest.Count; i++)
{
    if (i == 2)
    {
        <h3>@quest[2]</h3>
    }

}
@using (Html.BeginForm("PageQuest3", "QestAuthorizedUser"))
{
    @Html.CheckBoxFor(m => m.Status, false) @Html.Label(" 2 ")
    <br />
    @Html.CheckBox("answer2", false) @Html.Label(" 10 ")
    <br />
    @Html.CheckBox("answer3", false) @Html.Label(" 3 ")
    <br />
    <input type="submit" value="Сохранить" />

}
<br />
<br />
<a class=" btn btn-default" href="~/Home/TestForAuthorizeUsers">Вернуться к тестам</a>
@*показать результат теста или при продолжении + к другим баллам  ??? *@
<h3>@ViewBag.Status</h3>

TestForOski/Views/QestAuthorizedUser/PageQuest4.cshtml
@model TestForOski.Models.CheckBoxModel
<h2>Тест по Биологии </h2>

@{
    List<string> quest = new List<string>();
    foreach (var q in ViewBag.Questions)
    {
        if (q.IdCategory == 2)
        {
            // Собрали вопросы из конкретной категории
            quest.Add(q.Text);

        }
    }
}
<h2 style="color:maroon">Первый вопрос :</h2>

@for (int i = 0; i < quest.Count; i++)
{
    if (i == 0)
    {
        <h3>@quest[0]</h3>
    }

}
@using (Html.BeginForm("PageQuest4", "QestAuthorizedUser"))
{
    @Html.CheckBox("answer1", false) @Html.Label(" Саранча ")
    <br />
    @Html.CheckBox("answer2", false) @Html.Label(" Волк ")
    <br />
    @Html.CheckBoxFor(m => m.Status, false) @Html.Label(" Белка ")
    <br />
    <input type="submit" value="Сохранить" />

}
<br />
<br />
<a class=" btn btn-default" href="~/QestAuthorizedUser/PageQuest5">Продолжить</a>
<h3>@ViewBag.Status</h3>

TestForOski/Views/QestAuthorizedUser/PageQuest5.cshtml
@model TestForOski.Models.CheckBoxModel
<h2>Тест по Биологии </h2>

@{
    List<string> quest = new List<string>();
    foreach (var q in ViewBag.Questions)
    {
        if (q.IdCategory == 2)
        {
            // Собрали вопросы из конкретной категории
            quest.Add(q.Text);

        }
    }
}
<h2 style="color:maroon">Второй вопрос :</h2>

@for (int i = 0; i < quest.Count; i++)
{
    if (i == 1)
    {
        <h3>@quest[1]</h3>
    }

}

@using (Html.BeginForm("PageQuest5", "QestAuthorizedUser"))
{
    @Html.CheckBoxFor(m => m.Status, false) @Html.Label(" Беркут ")
    <br />
    @Html.CheckBox("answer2", false) @Html.Label(" Оса ")
    <br />
    @Html.CheckBox("answer3", false) @Html.Label(" Павлин ")
    <br />
    <input type="submit" value="Сохранить" />

}
<br />
<br />
<a class=" btn btn-default" href="~/QestAuthorizedUser/PageQuest6">Продолжить</a>
<h3>@ViewBag.Status</h3>

TestForOski/Views/QestAuthorizedUser/PageQuest6.cshtml
@model TestForOski.Models.CheckBoxModel
<h2>Тест по Биологии </h2>

@{
    List<string> quest = new List<string>();
    foreach (var q in ViewBag.Questions)
    {
        if (q.IdCategory == 2)
        {
            // Собрали вопросы из конкретной категории
            quest.Add(q.Text);

        }
    }
}
<h2 style="color:maroon">Третий вопрос :</h2>

@for (int i = 0; i < quest.Count; i++)
{
    if (i == 2)
    {
        <h3>@quest[2]</h3>
    }

}
@using (Html.BeginForm("PageQuest6", "QestAuthorizedUser"))
{
    @Html.CheckBox("answer1", false) @Html.Label(" Лиса ")
    <br />
    @Html.CheckBoxFor(m => m.Status, false) @Html.Label(" Жираф ")
    <br />
    @Html.CheckBox("answer3", false) @Html.Label(" Комар ")
    <br />
    <input type="submit" value="Сохранить" />

}
<br />
<br />
<a class=" btn btn-default" href="~/Home/TestForAuthorizeUsers">Вернуться к тестам</a>
@*показать результат теста или при продолжении, + к другим баллам ??? *@
<h3>@ViewBag.Status</h3>